### ISSUE TITLE
Export existing notes to markdown silently fails

### ISSUE THREAD

**Issue by njm2112** [Pradhyo/anki-markdown-notes#4]
Using Anki 2.0.52 and installing add-on using the ID through the Anki UI, I cannot get the existing notes exported using Tools > Export to Markdown Notes. The resulting file that is created is empty except for a level-1 heading with the name of the deck. (There is also a file called Default.md but I expected that to be empty because its the dummy deck that Anki provides before you create a deck of your own.)

Any chance you can point me in the right direction to fixing this? Not sure how to get to a debug console in Anki but if there is one available, I'm happy to provide the output that prints when I try to export to markdown...

Thanks!

**Comment by njm2112** [comment]
By way of update, the "Import Markdown Notes" function also fails, throwing the following error:

```console
An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "/Users/njm/Library/Application Support/Anki2/addons/Anki_Markdown_Notes.py", line 253, in importNotesUI
    deckCounter = processAllNotes(NotesPath)
  File "/Users/njm/Library/Application Support/Anki2/addons/Anki_Markdown_Notes.py", line 29, in processAllNotes
    existingNotesInFile = processFile(markdownFile, folderName)
  File "/Users/njm/Library/Application Support/Anki2/addons/Anki_Markdown_Notes.py", line 151, in processFile
    handleNote()
  File "/Users/njm/Library/Application Support/Anki2/addons/Anki_Markdown_Notes.py", line 128, in handleNote
    newID = addNote(frontText, backText, tag, model, deck)
  File "/Users/njm/Library/Application Support/Anki2/addons/Anki_Markdown_Notes.py", line 64, in addNote
    mw.col.addNote(note)
  File "anki/collection.pyc", line 253, in addNote
  File "anki/notes.pyc", line 54, in flush
  File "anki/db.pyc", line 76, in scalar
  File "anki/db.pyc", line 43, in execute
pysqlite2.dbapi2.ProgrammingError: You must not use 8-bit bytestrings unless you use a text_factory that can interpret 8-bit bytestrings (like text_factory = str). It is highly recommended that you instead just switch your application to Unicode strings.
```

**Comment by Pradhyo** [comment]
@njm2112 thanks for raising the issue.  

I will add some logging when I find some time and update here.

**Export** - the add-on only supports two types of built-in models "Basic" and "Basic (and reversed card)". Do you have any notes of these types? The add-on ignores other types because I don't have a convention for the other types.

**Import** - Based on [this](https://stackoverflow.com/questions/3425320/sqlite3-programmingerror-you-must-not-use-8-bit-bytestrings-unless-you-use-a-te), it is likely because of some encoding issue. I will add some logs to figure out which text is causing the issue.

**Comment by Pradhyo** [comment]
@njm2112 I believe this is now fixed thanks to @alexcthompson
